// Editable map data. Coordinates use the SVG viewBox space defined in index.html:
// x ranges from 0..2048 and y ranges from 0..1137.
//
// System fields:
// - name: unique display name used by routes and search
// - x/y: chart position in viewBox units
// - rating: numeric value shown beside the system and in the detail panel
// - group: fallback color group, matching the keys in constants.js colors
// - size: optional radius override for visually important systems
// - labelDx/labelDy/labelAnchor: optional label position override
//
// Routes are undirected pairs of system names. Keep route names in sync with systems[].
export const TIMEPILOT_MAP = {
  width: 2048,
  height: 1137,
  systems: [
    { name: "Alpha Andraste", x: 30, y: 166, rating: 30, group: "yellow" },
    { name: "Beta Andraste", x: 37, y: 150, rating: 20, group: "blue" },
    { name: "Carinae", x: 115, y: 203, rating: 20, group: "blue" },
    { name: "Eta Cassiopeia", x: 106, y: 219, rating: 20, group: "blue" },
    { name: "Piazzi", x: 295, y: 378, rating: 10, group: "green" },
    { name: "Bessel", x: 287, y: 394, rating: 10, group: "green" },
    { name: "Altair", x: 373, y: 453, rating: 15, group: "blue" },
    { name: "Van Maanen's Star", x: 64, y: 519, rating: 10, group: "green" },
    { name: "Sol", x: 321, y: 560, rating: 1, group: "green", size: 9 },
    { name: "Procyon A", x: 252, y: 598, rating: 10, group: "green" },
    { name: "Procyon B", x: 261, y: 582, rating: 5, group: "green" },
    { name: "Luyten's Star", x: 227, y: 586, rating: 5, group: "green", labelDx: -13, labelDy: 4, labelAnchor: "end" },
    { name: "Tau Ceti", x: 88, y: 623, rating: 10, group: "green" },
    { name: "Sirius", x: 240, y: 645, rating: 5, group: "green" },
    { name: "The Pup", x: 231, y: 660, rating: 10, group: "green" },
    { name: "Toliman", x: 375, y: 619, rating: 5, group: "green" },
    { name: "Alpha Centauri", x: 368, y: 634, rating: 1, group: "green", size: 8 },
    { name: "Wolf", x: 423, y: 565, rating: 1, group: "green" },
    { name: "Barnard's Star", x: 395, y: 530, rating: 1, group: "green" },
    { name: "Kapteyn's Star", x: 169, y: 786, rating: 10, group: "green" },
    { name: "Eridani", x: 48, y: 858, rating: 20, group: "blue" },
    { name: "Delta Pavonis", x: 349, y: 891, rating: 25, group: "yellow" },
    { name: "Sakharov", x: 466, y: 728, rating: 15, group: "blue" },
    { name: "Oborum Prime", x: 579, y: 736, rating: 20, group: "blue" },
    { name: "Oborum Proxima", x: 570, y: 751, rating: 25, group: "yellow" },
    { name: "Guniibuu", x: 571, y: 646, rating: 20, group: "blue" },
    { name: "Indum", x: 562, y: 661, rating: 20, group: "blue" },
    { name: "Linnaeus", x: 590, y: 688, rating: 45, group: "orange" },
    { name: "Aranae", x: 697, y: 645, rating: 15, group: "blue" },
    { name: "Olympus", x: 686, y: 666, rating: 10, group: "green" },
    { name: "Vega", x: 486, y: 214, rating: 25, group: "yellow" },
    { name: "Valo", x: 511, y: 475, rating: 5, group: "green" },
    { name: "Narion", x: 502, y: 491, rating: 1, group: "green" },
    { name: "Andromas", x: 597, y: 267, rating: 15, group: "blue" },
    { name: "Nikola", x: 676, y: 417, rating: 40, group: "orange" },
    { name: "Lunara", x: 750, y: 492, rating: 25, group: "yellow" },
    { name: "Cheyenne", x: 748, y: 382, rating: 1, group: "green", size: 8 },
    { name: "Maheo", x: 740, y: 398, rating: 1, group: "green" },
    { name: "Leviathan", x: 749, y: 449, rating: 55, group: "red" },
    { name: "Groombridge", x: 772, y: 233, rating: 25, group: "yellow" },
    { name: "McClure", x: 782, y: 177, rating: 20, group: "blue" },
    { name: "Bradbury", x: 792, y: 162, rating: 20, group: "blue" },
    { name: "Kumasi", x: 810, y: 272, rating: 25, group: "yellow" },
    { name: "Ursae Minoris", x: 830, y: 290, rating: 20, group: "blue" },
    { name: "Ursae Majoris", x: 820, y: 307, rating: 30, group: "yellow" },
    { name: "Rasalhague", x: 859, y: 253, rating: 40, group: "orange" },
    { name: "Nemeria", x: 793, y: 44, rating: 35, group: "orange" },
    { name: "Newton", x: 675, y: 81, rating: 55, group: "red" },
    { name: "Bardeen", x: 807, y: 96, rating: 70, group: "red" },
    { name: "Sagan", x: 921, y: 361, rating: 15, group: "blue" },
    { name: "Arcturus", x: 1006, y: 302, rating: 15, group: "blue" },
    { name: "Muphrid", x: 1019, y: 325, rating: 15, group: "blue" },
    { name: "Kryx", x: 974, y: 401, rating: 20, group: "blue" },
    { name: "Alpha Marae", x: 878, y: 430, rating: 45, group: "orange" },
    { name: "Beta Marae", x: 868, y: 446, rating: 45, group: "orange" },
    { name: "Schrodinger", x: 901, y: 470, rating: 65, group: "red" },
    { name: "Tidacha", x: 1031, y: 424, rating: 45, group: "orange" },
    { name: "Denebola", x: 1017, y: 442, rating: 30, group: "yellow" },
    { name: "Copernicus", x: 1117, y: 459, rating: 30, group: "yellow" },
    { name: "Copernicus Minor", x: 1107, y: 475, rating: 30, group: "yellow" },
    { name: "Lantana", x: 993, y: 582, rating: 30, group: "yellow" },
    { name: "Jaffa", x: 1038, y: 651, rating: 35, group: "orange" },
    { name: "Porrima", x: 1131, y: 630, rating: 30, group: "yellow" },
    { name: "Feynman", x: 831, y: 713, rating: 55, group: "red" },
    { name: "Xi Ophiuchi", x: 908, y: 729, rating: 50, group: "orange" },
    { name: "Zeta Ophiuchi", x: 903, y: 746, rating: 50, group: "orange" },
    { name: "Volii", x: 879, y: 767, rating: 5, group: "green", size: 8 },
    { name: "Alpha Tirna", x: 744, y: 1058, rating: 35, group: "orange" },
    { name: "Beta Tirna", x: 754, y: 1043, rating: 35, group: "orange" },
    { name: "Bolivar", x: 1154, y: 809, rating: 35, group: "orange" },
    { name: "Rivera", x: 1144, y: 826, rating: 35, group: "orange" },
    { name: "Nirvana", x: 1183, y: 858, rating: 40, group: "orange" },
    { name: "Alchiba", x: 1226, y: 1042, rating: 50, group: "orange" },
    { name: "Celebrai", x: 1169, y: 215, rating: 70, group: "red" },
    { name: "Zosma", x: 1181, y: 253, rating: 50, group: "orange" },
    { name: "Heisenberg", x: 1122, y: 367, rating: 55, group: "red" },
    { name: "Shoza", x: 1304, y: 238, rating: 35, group: "orange" },
    { name: "Freya", x: 1344, y: 70, rating: 40, group: "orange" },
    { name: "Ixyll", x: 1333, y: 100, rating: 40, group: "orange" },
    { name: "Bara", x: 1405, y: 317, rating: 45, group: "orange" },
    { name: "Moloch", x: 1390, y: 344, rating: 40, group: "orange" },
    { name: "Rutherford", x: 1378, y: 372, rating: 45, group: "orange" },
    { name: "Al-Battani", x: 1318, y: 469, rating: 40, group: "orange" },
    { name: "Khayyam", x: 1334, y: 486, rating: 40, group: "orange" },
    { name: "Ophion", x: 1378, y: 451, rating: 45, group: "orange" },
    { name: "Hyla", x: 1449, y: 479, rating: 40, group: "orange" },
    { name: "Sparta", x: 1457, y: 160, rating: 60, group: "red" },
    { name: "Charybdis", x: 1467, y: 300, rating: 65, group: "red" },
    { name: "Serpentis", x: 1516, y: 318, rating: 55, group: "red" },
    { name: "Nirah", x: 1474, y: 391, rating: 55, group: "red" },
    { name: "Leonis", x: 1498, y: 424, rating: 65, group: "red" },
    { name: "Decaran", x: 1376, y: 531, rating: 65, group: "red" },
    { name: "Heinlein", x: 1400, y: 576, rating: 45, group: "orange" },
    { name: "Delta Vulpes", x: 1364, y: 625, rating: 50, group: "orange" },
    { name: "Gamma Vulpes", x: 1354, y: 643, rating: 50, group: "orange" },
    { name: "Masada", x: 1382, y: 672, rating: 75, group: "red" },
    { name: "Bannoc Secondus", x: 1526, y: 588, rating: 50, group: "orange" },
    { name: "Bannoc", x: 1517, y: 603, rating: 50, group: "orange" },
    { name: "Bel", x: 1574, y: 566, rating: 55, group: "red" },
    { name: "Syrma", x: 1585, y: 623, rating: 55, group: "red" },
    { name: "Alpha Ternion", x: 1505, y: 642, rating: 60, group: "red" },
    { name: "Beta Ternion", x: 1495, y: 657, rating: 40, group: "orange" },
    { name: "Proxima Ternion", x: 1486, y: 670, rating: 65, group: "red" },
    { name: "Enlil", x: 1651, y: 654, rating: 65, group: "red" },
    { name: "Foucault", x: 1549, y: 749, rating: 60, group: "red" },
    { name: "Kang", x: 1586, y: 771, rating: 60, group: "red" },
    { name: "Zelazny", x: 1458, y: 875, rating: 60, group: "red" },
    { name: "Katydid", x: 1339, y: 1120, rating: 75, group: "red" },
    { name: "Marduk", x: 1682, y: 985, rating: 70, group: "red" },
    { name: "Algorab", x: 1780, y: 1071, rating: 70, group: "red" },
    { name: "Maal", x: 1715, y: 425, rating: 60, group: "red" },
    { name: "Verne", x: 1815, y: 480, rating: 70, group: "red" },
    { name: "Pyraas", x: 1795, y: 187, rating: 70, group: "red" },
    { name: "Rana", x: 1751, y: 237, rating: 65, group: "red" },
    { name: "Strix", x: 1852, y: 274, rating: 70, group: "red" },
    { name: "Fermi", x: 1898, y: 256, rating: 75, group: "red" },
    { name: "Bohr", x: 1951, y: 296, rating: 75, group: "red" },
    { name: "Huygens", x: 1945, y: 593, rating: 75, group: "red" },
    { name: "Hawking", x: 1910, y: 629, rating: 75, group: "red" },
    { name: "Archimedes", x: 1820, y: 671, rating: 75, group: "red" }
  ],
  routes: [
    ["Alpha Andraste", "Piazzi"], ["Beta Andraste", "Bessel"], ["Carinae", "Piazzi"], ["Eta Cassiopeia", "Bessel"],
    ["Piazzi", "Bessel"], ["Bessel", "Sol"], ["Bessel", "Van Maanen's Star"], ["Bessel", "Altair"],
    ["Sol", "Procyon A"], ["Sol", "Procyon B"], ["Sol", "Luyten's Star"], ["Sol", "Toliman"], ["Sol", "Alpha Centauri"], ["Sol", "Barnard's Star"],
    ["Alpha Centauri", "Sirius"], ["Alpha Centauri", "The Pup"], ["Alpha Centauri", "Tau Ceti"], ["Alpha Centauri", "Kapteyn's Star"], ["Alpha Centauri", "Eridani"], ["Alpha Centauri", "Delta Pavonis"],
    ["Alpha Centauri", "Wolf"], ["Alpha Centauri", "Sakharov"], ["Alpha Centauri", "Guniibuu"], ["Alpha Centauri", "Lunara"],
    ["Vega", "Narion"], ["Narion", "Valo"], ["Valo", "Nikola"], ["Valo", "Andromas"], ["Andromas", "Nemeria"],
    ["Nemeria", "Newton"], ["Newton", "Cheyenne"], ["Bardeen", "Celebrai"], ["Groombridge", "Cheyenne"], ["Groombridge", "Bradbury"], ["Groombridge", "McClure"],
    ["Groombridge", "Kumasi"], ["Kumasi", "Ursae Minoris"], ["Ursae Minoris", "Ursae Majoris"], ["Kumasi", "Rasalhague"],
    ["Cheyenne", "Maheo"], ["Cheyenne", "Sagan"], ["Cheyenne", "Arcturus"], ["Cheyenne", "Kryx"], ["Maheo", "Leviathan"], ["Nikola", "Leviathan"], ["Nikola", "Lunara"],
    ["Lunara", "Feynman"], ["Lunara", "Alpha Marae"], ["Lunara", "Beta Marae"], ["Lunara", "Schrodinger"], ["Lunara", "Alpha Centauri"],
    ["Alpha Marae", "Beta Marae"], ["Beta Marae", "Schrodinger"], ["Beta Marae", "Tidacha"], ["Tidacha", "Denebola"], ["Denebola", "Copernicus"], ["Copernicus", "Copernicus Minor"],
    ["Arcturus", "Muphrid"], ["Muphrid", "Heisenberg"], ["Kryx", "Tidacha"], ["Kryx", "Lantana"], ["Lantana", "Jaffa"], ["Jaffa", "Porrima"],
    ["Feynman", "Volii"], ["Volii", "Xi Ophiuchi"], ["Xi Ophiuchi", "Zeta Ophiuchi"], ["Volii", "Alpha Tirna"], ["Volii", "Bolivar"], ["Bolivar", "Rivera"], ["Rivera", "Nirvana"], ["Rivera", "Alchiba"],
    ["Celebrai", "Zosma"], ["Celebrai", "Shoza"], ["Zosma", "Shoza"], ["Shoza", "Freya"], ["Shoza", "Ixyll"], ["Shoza", "Bara"], ["Shoza", "Rutherford"],
    ["Bara", "Moloch"], ["Moloch", "Rutherford"], ["Rutherford", "Nirah"], ["Rutherford", "Al-Battani"], ["Al-Battani", "Khayyam"], ["Ophion", "Hyla"], ["Khayyam", "Hyla"],
    ["Bara", "Charybdis"], ["Charybdis", "Serpentis"], ["Sparta", "Charybdis"], ["Nirah", "Leonis"], ["Leonis", "Maal"], ["Maal", "Verne"],
    ["Pyraas", "Rana"], ["Rana", "Strix"], ["Strix", "Fermi"], ["Strix", "Bohr"], ["Maal", "Strix"],
    ["Decaran", "Gamma Vulpes"], ["Gamma Vulpes", "Delta Vulpes"], ["Heinlein", "Delta Vulpes"], ["Delta Vulpes", "Bannoc"], ["Bannoc", "Bannoc Secondus"],
    ["Bannoc", "Alpha Ternion"], ["Alpha Ternion", "Beta Ternion"], ["Beta Ternion", "Proxima Ternion"], ["Alpha Ternion", "Syrma"], ["Syrma", "Enlil"], ["Bel", "Syrma"],
    ["Masada", "Proxima Ternion"], ["Foucault", "Kang"], ["Zelazny", "Katydid"], ["Zelazny", "Marduk"], ["Marduk", "Algorab"], ["Zelazny", "Alchiba"],
    ["Hawking", "Archimedes"], ["Huygens", "Hawking"], ["Archimedes", "Enlil"], ["Maal", "Archimedes"]
  ]
};
