window.TIMEPILOT_SYSTEM_DETAILS = {
  "Alpha Andraste": {
    "faction": "None",
    "spectralClass": "G5",
    "catalogueId": "GL 53A",
    "temperature": "5575K",
    "mass": "0.93 SM",
    "radius": "647559",
    "magnitude": "5.77",
    "planets": "6",
    "moons": "1"
  },
  "Beta Andraste": {
    "faction": "None",
    "spectralClass": "M3",
    "catalogueId": "GL 538",
    "temperature": "3280K",
    "mass": "0.31SM",
    "radius": "309157",
    "magnitude": "11.60",
    "planets": "1",
    "moons": "4"
  },
  "Carinae": {
    "faction": "None",
    "spectralClass": "K7",
    "catalogueId": "GL 348",
    "temperature": "4045K",
    "mass": "0.56SM",
    "radius": "459589",
    "magnitude": "8.63",
    "planets": "5",
    "moons": "9"
  },
  "Eta Cassiopeia": {
    "faction": "None",
    "planets": "4",
    "moons": "5"
  },
  "Piazzi": {
    "spectralClass": "K5",
    "catalogueId": "GL 820A",
    "temperature": "4375K",
    "mass": "0.69SM",
    "radius": "515262",
    "magnitude": "7.48",
    "planets": "7",
    "moons": "14"
  },
  "Bessel": {
    "faction": "none",
    "magnitude": "TBD",
    "planets": "3",
    "moons": "2"
  },
  "Altair": {
    "faction": "None",
    "spectralClass": "A7",
    "catalogueId": "GL 768",
    "temperature": "6900K",
    "mass": "1.78SM",
    "radius": "1251900",
    "magnitude": "2.21",
    "planets": "5",
    "moons": "8"
  },
  "Van Maanen's Star": {
    "spectralClass": "WD",
    "catalogueId": "GL 35",
    "temperature": "6130 K",
    "mass": "0.70SM",
    "radius": "9609",
    "magnitude": "14.22",
    "planets": "1",
    "moons": "0"
  },
  "Sol": {
    "faction": "United Colonies",
    "spectralClass": "G2V",
    "temperature": "5772K",
    "mass": "1.0SM",
    "radius": "695800",
    "magnitude": "4.83",
    "planets": "9",
    "moons": "21"
  },
  "Procyon A": {
    "spectralClass": "F5",
    "catalogueId": "GL 280A",
    "temperature": "6530K",
    "mass": "1.49SM",
    "radius": "1424384",
    "magnitude": "2.67",
    "planets": "6",
    "moons": "9"
  },
  "Procyon B": {
    "spectralClass": "WD",
    "catalogueId": "GL 280B",
    "temperature": "7740K",
    "mass": "0.60SM",
    "radius": "8592",
    "magnitude": "12.98",
    "planets": "1",
    "moons": "0"
  },
  "Luyten's Star": {
    "faction": "None",
    "spectralClass": "M1",
    "catalogueId": "GL 273",
    "temperature": "3150K",
    "mass": "0.25SM",
    "radius": "243721",
    "magnitude": "11.93",
    "planets": "1",
    "moons": "0"
  },
  "Tau Ceti": {
    "faction": "None",
    "spectralClass": "G8",
    "catalogueId": "GL 71",
    "temperature": "5320K",
    "mass": "0.78SM",
    "radius": "552203",
    "magnitude": "5.67",
    "planets": "9",
    "moons": "9"
  },
  "Sirius": {
    "faction": "None",
    "spectralClass": "A1",
    "catalogueId": "GL 244A",
    "temperature": "9940K",
    "mass": "2.06SM",
    "radius": "1190001",
    "magnitude": "1.45",
    "planets": "3",
    "moons": "3"
  },
  "The Pup": {
    "faction": "None",
    "spectralClass": "WD",
    "catalogueId": "GL 244B",
    "temperature": "25200K",
    "mass": "1.01SM",
    "radius": "5564",
    "magnitude": "11.18",
    "planets": "1",
    "moons": "0"
  },
  "Toliman": {
    "faction": "None",
    "spectralClass": "K1",
    "catalogueId": "GL 559B",
    "temperature": "5260K",
    "mass": "0.90SM",
    "radius": "601086",
    "magnitude": "5.73",
    "planets": "2",
    "moons": "3"
  },
  "Alpha Centauri": {
    "faction": "United Colonies",
    "spectralClass": "G2",
    "catalogueId": "GL 559A",
    "temperature": "5790K",
    "mass": "1.10SM",
    "radius": "862420",
    "magnitude": "4.37",
    "planets": "4",
    "moons": "8"
  },
  "Wolf": {
    "faction": "United Colonies",
    "spectralClass": "M6",
    "catalogueId": "GL 406",
    "temperature": "2860K",
    "mass": "0.08SM",
    "radius": "111415",
    "magnitude": "16.55",
    "planets": "2",
    "moons": "1"
  },
  "Barnard's Star": {
    "spectralClass": "M4",
    "catalogueId": "GL 699",
    "temperature": "3130K",
    "mass": "0.14SM",
    "radius": "136484",
    "magnitude": "13.23"
  },
  "Kapteyn's Star": {
    "spectralClass": "M0",
    "catalogueId": "GL 191",
    "temperature": "3570K",
    "mass": "0.28SM",
    "radius": "202636",
    "magnitude": "10.89",
    "planets": "2",
    "moons": "0"
  },
  "Eridani": {
    "spectralClass": "G8",
    "catalogueId": "GL 139",
    "temperature": "5400K",
    "mass": "0.69SM",
    "radius": "639860",
    "magnitude": "5.35",
    "planets": "9",
    "moons": "14"
  },
  "Delta Pavonis": {
    "spectralClass": "G5",
    "catalogueId": "GL 780",
    "temperature": "5570K",
    "mass": "0.99SM",
    "radius": "833527",
    "magnitude": "4.61"
  },
  "Sakharov": {
    "faction": "None",
    "spectralClass": "M3",
    "catalogueId": "GL 674",
    "temperature": "3600K",
    "mass": "0.36SM",
    "radius": "352327",
    "magnitude": "11.09",
    "planets": "1",
    "moons": "1"
  },
  "Oborum Prime": {
    "spectralClass": "K3",
    "catalogueId": "GL 667A",
    "temperature": "4705K",
    "mass": "0.72SM",
    "radius": "529223",
    "magnitude": "7.07",
    "planets": "4",
    "moons": "6"
  },
  "Oborum Proxima": {
    "faction": "None",
    "spectralClass": "M2",
    "catalogueId": "GL 667C",
    "temperature": "3700K",
    "mass": "0.30SM",
    "radius": "292465",
    "magnitude": "11.02",
    "planets": "1",
    "moons": "0"
  },
  "Guniibuu": {
    "spectralClass": "K2",
    "catalogueId": "GL 663A",
    "temperature": "4870K",
    "mass": "0.74SM",
    "radius": "561217",
    "magnitude": "5.46"
  },
  "Indum": {
    "faction": "None",
    "spectralClass": "K1",
    "catalogueId": "GL 663B",
    "temperature": "5035K",
    "mass": "0.76SM",
    "radius": "576536",
    "magnitude": "6.18",
    "planets": "5",
    "moons": "10"
  },
  "Linnaeus": {
    "spectralClass": "G5",
    "catalogueId": "GL 722",
    "temperature": "5575K",
    "mass": "0.93SM",
    "radius": "647559",
    "magnitude": "5.26",
    "planets": "7",
    "moons": "5"
  },
  "Aranae": {
    "faction": "None",
    "planets": "5",
    "moons": "6"
  },
  "Olympus": {
    "faction": "None",
    "spectralClass": "K4",
    "catalogueId": "GL 570A",
    "temperature": "4540K",
    "mass": "0.71SM",
    "radius": "530580",
    "magnitude": "6.89",
    "planets": "6",
    "moons": "7"
  },
  "Vega": {
    "faction": "None",
    "spectralClass": "A0",
    "catalogueId": "GL 721",
    "temperature": "9600K",
    "mass": "2.13SM",
    "radius": "1642771",
    "magnitude": "0.60",
    "planets": "2",
    "moons": "8"
  },
  "Valo": {
    "faction": "None",
    "spectralClass": "K5",
    "catalogueId": "GL 792B",
    "temperature": "5375K",
    "mass": "0.69SM",
    "radius": "515262",
    "magnitude": "7.47",
    "planets": "5",
    "moons": "6"
  },
  "Narion": {
    "faction": "Freestar Collective",
    "spectralClass": "K0",
    "catalogueId": "GL 702A",
    "temperature": "5200K",
    "mass": "0.78SM",
    "radius": "591855",
    "magnitude": "5.49",
    "planets": "7",
    "moons": "8"
  },
  "Andromas": {
    "faction": "None",
    "spectralClass": "G5",
    "catalogueId": "GL 695A",
    "temperature": "5590K",
    "mass": "0.93SM",
    "radius": "647559",
    "magnitude": "3.82",
    "planets": "6",
    "moons": "5"
  },
  "Nikola": {
    "faction": "None",
    "spectralClass": "G5",
    "catalogueId": "NN 4056",
    "temperature": "5575K",
    "mass": "0.93SM",
    "radius": "647559",
    "magnitude": "11.12",
    "planets": "10",
    "moons": "9"
  },
  "Lunara": {
    "spectralClass": "G4",
    "catalogueId": "GL 660A",
    "temperature": "5660K",
    "mass": "0.95SM",
    "radius": "663805",
    "magnitude": "11.4",
    "planets": "8",
    "moons": "17"
  },
  "Cheyenne": {
    "faction": "Freestar Collective",
    "spectralClass": "G8",
    "catalogueId": "GL 566A",
    "temperature": "5320K",
    "mass": "0.84SM",
    "radius": "614136",
    "magnitude": "5.40",
    "planets": "9",
    "moons": "26"
  },
  "Maheo": {
    "faction": "None",
    "spectralClass": "K4",
    "catalogueId": "GL 566B",
    "temperature": "4540K",
    "mass": "0.70SM",
    "radius": "530580",
    "magnitude": "7.84",
    "planets": "7",
    "moons": "9"
  },
  "Leviathan": {
    "faction": "None",
    "spectralClass": "K0",
    "catalogueId": "GL 711",
    "temperature": "4890K",
    "mass": "2.00SM",
    "radius": "4101364",
    "magnitude": "1.88",
    "planets": "7",
    "moons": "3"
  },
  "Groombridge": {
    "spectralClass": "G8",
    "catalogueId": "GL 451A",
    "temperature": "4760K",
    "mass": "0.66SM",
    "radius": "474212",
    "magnitude": "6.62",
    "planets": "8",
    "moons": "18"
  },
  "McClure": {
    "faction": "None",
    "spectralClass": "K0",
    "catalogueId": "GL 635B",
    "temperature": "5200K",
    "mass": "0.78SM",
    "radius": "591855",
    "magnitude": "5.23",
    "planets": "3",
    "moons": "4"
  },
  "Bradbury": {
    "faction": "None",
    "spectralClass": "F9",
    "catalogueId": "GL 635A",
    "temperature": "5820K",
    "mass": "1.14SM",
    "radius": "752004",
    "magnitude": "2.66",
    "planets": "5",
    "moons": "4"
  },
  "Kumasi": {
    "spectralClass": "GB",
    "catalogueId": "GL 434",
    "temperature": "5320K",
    "mass": "0.84 SM",
    "radius": "614136",
    "magnitude": "5.39",
    "planets": "9",
    "moons": "19"
  },
  "Ursae Minoris": {
    "faction": "None",
    "spectralClass": "G2",
    "catalogueId": "GL 423B",
    "temperature": "5700K",
    "mass": "0.86SM",
    "radius": "640596",
    "magnitude": "4.71",
    "planets": "3",
    "moons": "3"
  },
  "Ursae Majoris": {
    "faction": "None",
    "spectralClass": "F8",
    "catalogueId": "GL 423A",
    "temperature": "6000K",
    "mass": "0.97SM",
    "radius": "710226",
    "magnitude": "4.24",
    "planets": "3",
    "moons": "3"
  },
  "Rasalhague": {
    "spectralClass": "A5",
    "catalogueId": "GL 681",
    "temperature": "8040K",
    "mass": "2.10SM",
    "radius": "1808300",
    "magnitude": "1.21",
    "planets": "4",
    "moons": "3"
  },
  "Nemeria": {
    "planets": "4 (at least)",
    "moons": "1 (at least)"
  },
  "Newton": {
    "faction": "None",
    "spectralClass": "F6",
    "catalogueId": "GL 725.2",
    "temperature": "6510K",
    "mass": "1.26SM",
    "radius": "814671",
    "magnitude": "2.77",
    "planets": "6",
    "moons": "6"
  },
  "Bardeen": {
    "spectralClass": "G8",
    "catalogueId": "GJ 1229",
    "temperature": "5320K",
    "mass": "0.84SM",
    "radius": "614136",
    "magnitude": "5.12",
    "planets": "7",
    "moons": "13"
  },
  "Sagan": {
    "faction": "None",
    "spectralClass": "M2",
    "catalogueId": "GL 569A",
    "temperature": "3420K",
    "mass": "0.36SM",
    "radius": "352327",
    "magnitude": "10.18",
    "planets": "1",
    "moons": "0"
  },
  "Arcturus": {
    "planets": "3 (at least)"
  },
  "Muphrid": {
    "faction": "None",
    "spectralClass": "G0",
    "catalogueId": "GL 534",
    "temperature": "6100K",
    "mass": "1.10SM",
    "radius": "731114",
    "magnitude": "2.39",
    "planets": "8",
    "moons": "21"
  },
  "Kryx": {
    "faction": "Crimson Fleet",
    "spectralClass": "G0",
    "catalogueId": "GL 598",
    "temperature": "6000K",
    "mass": "1.10SM",
    "radius": "731114",
    "magnitude": "4.00",
    "planets": "1",
    "moons": "7"
  },
  "Alpha Marae": {
    "faction": "None",
    "spectralClass": "G8",
    "catalogueId": "GL 678A",
    "temperature": "5500K",
    "mass": "1.10SM",
    "radius": "1182350",
    "magnitude": "4.24",
    "planets": "5",
    "moons": "7"
  },
  "Beta Marae": {
    "faction": "None",
    "spectralClass": "G8",
    "catalogueId": "GL 678B",
    "temperature": "5500K",
    "mass": "0.84SM",
    "radius": "15318600",
    "magnitude": "5.11",
    "planets": "6",
    "moons": "15"
  },
  "Schrodinger": {
    "faction": "None",
    "spectralClass": "F3",
    "catalogueId": "GL 699.2",
    "temperature": "7005K",
    "mass": "1.46SM",
    "radius": "1363878",
    "magnitude": "2.75",
    "planets": "8",
    "moons": "14"
  },
  "Tidacha": {
    "spectralClass": "G8",
    "catalogueId": "GL 641",
    "temperature": "5320K",
    "mass": "0.84SM",
    "radius": "614136",
    "magnitude": "5.46",
    "planets": "1",
    "moons": "3"
  },
  "Denebola": {
    "faction": "Freestar Collective",
    "spectralClass": "A3",
    "catalogueId": "GL 448",
    "temperature": "8500K",
    "mass": "1.77SM",
    "radius": "1201824",
    "magnitude": "1.93",
    "planets": "3",
    "moons": "5"
  },
  "Copernicus": {
    "faction": "None",
    "spectralClass": "G5",
    "catalogueId": "GL 596.1A",
    "temperature": "5575K",
    "mass": "0.93SM",
    "radius": "647559",
    "magnitude": "5.03",
    "planets": "8",
    "moons": "7"
  },
  "Copernicus Minor": {
    "faction": "None",
    "spectralClass": "M6",
    "catalogueId": "GL 596.1B",
    "temperature": "2860K",
    "mass": "0.17SM",
    "radius": "178717",
    "magnitude": "11.16",
    "planets": "1",
    "moons": "2"
  },
  "Lantana": {
    "faction": "None",
    "spectralClass": "F8",
    "catalogueId": "GL 449",
    "temperature": "6130K",
    "mass": "1.18 SM",
    "radius": "772893",
    "magnitude": "3.39",
    "planets": "9",
    "moons": "12"
  },
  "Jaffa": {
    "spectralClass": "G1",
    "catalogueId": "GL 616",
    "temperature": "5915K",
    "mass": "1.05SM",
    "radius": "717189",
    "magnitude": "4.77",
    "planets": "8",
    "moons": "12"
  },
  "Porrima": {
    "faction": "None",
    "spectralClass": "F0",
    "catalogueId": "GL 482A",
    "temperature": "7500K",
    "mass": "1.55SM",
    "radius": "973700",
    "magnitude": "2.40",
    "planets": "6",
    "moons": "15"
  },
  "Feynman": {
    "faction": "None",
    "spectralClass": "F6",
    "catalogueId": "GL 692",
    "temperature": "6510K",
    "mass": "1.26SM",
    "radius": "814671",
    "magnitude": "3.62",
    "planets": "9",
    "moons": "14"
  },
  "Xi Ophiuchi": {
    "faction": "None",
    "spectralClass": "F2",
    "temperature": "3900K",
    "mass": "1.36SM",
    "radius": "973700",
    "magnitude": "3.19",
    "planets": "9",
    "moons": "14"
  },
  "Zeta Ophiuchi": {
    "faction": "None",
    "spectralClass": "K3",
    "catalogueId": "GL 670B",
    "temperature": "4705K",
    "mass": "0.72SM",
    "radius": "545899",
    "magnitude": "7.69",
    "planets": "6",
    "moons": "13"
  },
  "Volii": {
    "faction": "Freestar Collective",
    "spectralClass": "G5",
    "catalogueId": "GL 506",
    "temperature": "5575K",
    "mass": "0.93SM",
    "radius": "647559",
    "magnitude": "5.07",
    "planets": "6",
    "moons": "5"
  },
  "Alpha Tirna": {
    "spectralClass": "G3",
    "catalogueId": "GL 42A",
    "temperature": "5745K",
    "mass": "0.97SM",
    "radius": "680053",
    "magnitude": "5.06",
    "planets": "10",
    "moons": "21"
  },
  "Beta Tirna": {
    "faction": "None",
    "spectralClass": "M5",
    "catalogueId": "GL 4428",
    "temperature": "3000K",
    "mass": "0.21SM",
    "radius": "222816",
    "magnitude": "15.17",
    "planets": "1",
    "moons": "0"
  },
  "Bolivar": {
    "faction": "None",
    "spectralClass": "M3",
    "catalogueId": "NN 3727A",
    "temperature": "3280K",
    "mass": "0.31SM",
    "radius": "309157",
    "magnitude": "10.55",
    "planets": "1",
    "moons": "0"
  },
  "Rivera": {
    "faction": "None",
    "spectralClass": "G5",
    "catalogueId": "NN 3728B",
    "temperature": "5575K",
    "mass": "0.93SM",
    "radius": "647559",
    "magnitude": "10.59",
    "planets": "5",
    "moons": "6"
  },
  "Nirvana": {
    "spectralClass": "K0",
    "catalogueId": "GL 454",
    "temperature": "5200K",
    "mass": "0.78SM",
    "radius": "591855",
    "magnitude": "5.01",
    "planets": "4",
    "moons": "3"
  },
  "Alchiba": {
    "spectralClass": "F0",
    "catalogueId": "FL 455.3",
    "temperature": "7040K",
    "mass": "1.38SM",
    "radius": "904150",
    "magnitude": "3.14",
    "planets": "10",
    "moons": "18"
  },
  "Celebrai": {
    "faction": "None",
    "spectralClass": "K2",
    "temperature": "4870K",
    "mass": "1.13SM",
    "radius": "8638110",
    "magnitude": "0.76",
    "planets": "4",
    "moons": "3"
  },
  "Zosma": {
    "faction": "None",
    "spectralClass": "A4",
    "catalogueId": "GL 419",
    "temperature": "8900K",
    "mass": "2.20SM",
    "radius": "1488370",
    "magnitude": "1.29",
    "planets": "5",
    "moons": "8"
  },
  "Heisenberg": {
    "spectralClass": "F9",
    "catalogueId": "GL 654.1",
    "temperature": "6015K",
    "mass": "1.14SM",
    "radius": "752004",
    "magnitude": "4.42",
    "planets": "10",
    "moons": "9"
  },
  "Shoza": {
    "faction": "None",
    "spectralClass": "F7",
    "catalogueId": "GL 527A",
    "temperature": "6360K",
    "mass": "1.22SM",
    "radius": "793782",
    "magnitude": "3.53",
    "planets": "9",
    "moons": "11"
  },
  "Freya": {
    "spectralClass": "G2",
    "catalogueId": "GL 564",
    "temperature": "5830K",
    "mass": "1.00SM",
    "radius": "696300",
    "magnitude": "4.56",
    "planets": "9",
    "moons": "8"
  },
  "Ixyll": {
    "faction": "None",
    "spectralClass": "G7",
    "catalogueId": "GL 486.1",
    "temperature": "5405K",
    "mass": "0.87SM",
    "radius": "625277",
    "magnitude": "5.14",
    "planets": "9",
    "moons": "17"
  },
  "Bara": {
    "faction": "None",
    "spectralClass": "G5",
    "catalogueId": "GL 512.1",
    "temperature": "5575K",
    "mass": "0.93SM",
    "radius": "647559",
    "magnitude": "3.69",
    "planets": "7",
    "moons": "10"
  },
  "Moloch": {
    "spectralClass": "G8",
    "catalogueId": "GL 538",
    "temperature": "5320K",
    "mass": "0.84SM",
    "radius": "614136",
    "magnitude": "5.11",
    "planets": "7",
    "moons": "7"
  },
  "Rutherford": {
    "faction": "None",
    "spectralClass": "G0",
    "catalogueId": "GL 504",
    "temperature": "6000K",
    "mass": "1.10SM",
    "radius": "731114",
    "magnitude": "3.96",
    "planets": "6",
    "moons": "15"
  },
  "Al-Battani": {
    "faction": "None",
    "spectralClass": "G5",
    "catalogueId": "NN 3781A",
    "temperature": "5575K",
    "mass": "0.93SM",
    "radius": "647559",
    "magnitude": "6.11",
    "planets": "8",
    "moons": "12"
  },
  "Khayyam": {
    "spectralClass": "G4",
    "catalogueId": "NN 3782B",
    "temperature": "5660K",
    "mass": "0.95SM",
    "radius": "663805",
    "magnitude": "6.30",
    "planets": "6",
    "moons": "12"
  },
  "Ophion": {
    "faction": "None",
    "spectralClass": "K0",
    "catalogueId": "GL 580A",
    "temperature": "5200K",
    "mass": "0.78SM",
    "radius": "591855",
    "magnitude": "5.34",
    "planets": "1",
    "moons": "1"
  },
  "Hyla": {
    "spectralClass": "G1",
    "catalogueId": "GL 547",
    "temperature": "5915K",
    "mass": "1.05SM",
    "radius": "717189",
    "magnitude": "5.07",
    "planets": "8",
    "moons": "14"
  },
  "Sparta": {
    "faction": "None",
    "spectralClass": "G8",
    "catalogueId": "GL 615.1A",
    "temperature": "5320K",
    "mass": "0.84SM",
    "radius": "614136",
    "magnitude": "4.81",
    "planets": "8",
    "moons": "13"
  },
  "Charybdis": {
    "spectralClass": "G0",
    "catalogueId": "NN 3669A",
    "temperature": "6000K",
    "mass": "1.10SM",
    "radius": "731114",
    "magnitude": "4.43",
    "planets": "9",
    "moons": "10"
  },
  "Serpentis": {
    "spectralClass": "K2",
    "catalogueId": "GL 596.2",
    "temperature": "4870K",
    "mass": "0.74SM",
    "radius": "8346020",
    "magnitude": "0.85",
    "planets": "6",
    "moons": "9"
  },
  "Nirah": {
    "faction": "None",
    "spectralClass": "G8",
    "catalogueId": "NN 3917",
    "temperature": "5320K",
    "mass": "0.84SM",
    "radius": "614136",
    "magnitude": "5.79",
    "planets": "5",
    "moons": "2"
  },
  "Leonis": {
    "faction": "None",
    "spectralClass": "F2",
    "temperature": "7170K",
    "mass": "1.54SM",
    "radius": "1460550",
    "magnitude": "2.12",
    "planets": "9",
    "moons": "8"
  },
  "Decaran": {
    "faction": "None",
    "spectralClass": "G9",
    "catalogueId": "NN 3969",
    "temperature": "5235K",
    "mass": "0.81SM",
    "radius": "602995",
    "magnitude": "10.22",
    "planets": "9",
    "moons": "7"
  },
  "Heinlein": {
    "faction": "None",
    "spectralClass": "F2",
    "catalogueId": "WO 9491",
    "temperature": "7170K",
    "mass": "1.99SM",
    "radius": "877338",
    "magnitude": "2.56",
    "planets": "7",
    "moons": "16"
  },
  "Delta Vulpes": {
    "faction": "None",
    "spectralClass": "K2",
    "catalogueId": "GL 586B",
    "temperature": "4870K",
    "mass": "0.73SM",
    "radius": "555705",
    "magnitude": "6.01",
    "planets": "7",
    "moons": "8"
  },
  "Gamma Vulpes": {
    "faction": "None",
    "spectralClass": "K2",
    "catalogueId": "GL 586A",
    "temperature": "4870K",
    "mass": "0.74SM",
    "radius": "561217",
    "magnitude": "5.32",
    "planets": "4",
    "moons": "9"
  },
  "Masada": {
    "faction": "None",
    "spectralClass": "G2",
    "catalogueId": "GL 650",
    "temperature": "5830K",
    "mass": "1.00SM",
    "radius": "696300",
    "magnitude": "4.93",
    "planets": "9",
    "moons": "8"
  },
  "Bannoc Secondus": {
    "faction": "None",
    "spectralClass": "M4",
    "catalogueId": "GL 544B",
    "temperature": "3140K",
    "mass": "0.265M",
    "radius": "265986",
    "magnitude": "13.51",
    "planets": "1",
    "moons": "0"
  },
  "Bannoc": {
    "faction": "None",
    "spectralClass": "K1",
    "catalogueId": "GL 544A",
    "temperature": "5035K",
    "mass": "0.76SM",
    "radius": "576536",
    "magnitude": "5.98",
    "planets": "4",
    "moons": "3"
  },
  "Bel": {
    "faction": "None",
    "spectralClass": "G0",
    "catalogueId": "NN 3830",
    "temperature": "6000K",
    "mass": "1.10SM",
    "radius": "731114",
    "magnitude": "5.33",
    "planets": "7",
    "moons": "11"
  },
  "Syrma": {
    "spectralClass": "F7",
    "catalogueId": "WO 9473",
    "temperature": "6345K",
    "mass": "1.22SM",
    "radius": "793782",
    "magnitude": "2.33",
    "planets": "7",
    "moons": "11"
  },
  "Alpha Ternion": {
    "faction": "None",
    "spectralClass": "G8",
    "catalogueId": "WO 954OC",
    "temperature": "5320K",
    "mass": "0.84SM",
    "radius": "613431",
    "magnitude": "5.36",
    "planets": "9",
    "moons": "8"
  },
  "Beta Ternion": {
    "spectralClass": "F6",
    "catalogueId": "WO 9540A",
    "temperature": "6510K",
    "mass": "1.29SM",
    "radius": "820690",
    "magnitude": "2.9",
    "planets": "3",
    "moons": "2"
  },
  "Proxima Ternion": {
    "faction": "None",
    "spectralClass": "F6",
    "catalogueId": "WO 9540B",
    "temperature": "6510K",
    "mass": "1.26SM",
    "radius": "813735",
    "magnitude": "3.06",
    "planets": "4",
    "moons": "4"
  },
  "Enlil": {
    "spectralClass": "G8",
    "catalogueId": "WO 9541A",
    "temperature": "5320K",
    "mass": "0.84SM",
    "radius": "614136",
    "magnitude": "5.42",
    "planets": "7",
    "moons": "8"
  },
  "Foucault": {
    "spectralClass": "F3",
    "catalogueId": "GL 563.4",
    "temperature": "7005K",
    "mass": "1.97SM",
    "radius": "862420",
    "magnitude": "3.34",
    "planets": "8",
    "moons": "21"
  },
  "Kang": {
    "faction": "None",
    "spectralClass": "G6",
    "temperature": "5490K",
    "mass": "0.90SM",
    "radius": "636418",
    "magnitude": "5.36",
    "planets": "8",
    "moons": "12"
  },
  "Zelazny": {
    "spectralClass": "G0",
    "catalogueId": "Wo 9390A",
    "temperature": "6000 K",
    "mass": "1.10 SM",
    "radius": "731,114",
    "magnitude": "5.08",
    "planets": "8",
    "moons": "10"
  },
  "Katydid": {
    "spectralClass": "A9",
    "temperature": "7525K",
    "mass": "1.78SM",
    "radius": "960894",
    "magnitude": "2.04",
    "planets": "3",
    "moons": "2"
  },
  "Marduk": {
    "faction": "None",
    "spectralClass": "G1",
    "catalogueId": "GL 469.2A",
    "temperature": "5915K",
    "mass": "1.05SM",
    "radius": "717189",
    "magnitude": "4.41",
    "planets": "9",
    "moons": "9"
  },
  "Algorab": {
    "spectralClass": "B9",
    "temperature": "10500K",
    "mass": "2.74SM",
    "radius": "1808300",
    "magnitude": "0.81",
    "planets": "3",
    "moons": "5"
  },
  "Maal": {
    "faction": "None",
    "spectralClass": "F8",
    "temperature": "6180K",
    "mass": "1.18SM",
    "radius": "772893",
    "magnitude": "3.01",
    "planets": "10",
    "moons": "13"
  },
  "Verne": {
    "spectralClass": "G5",
    "catalogueId": "WO 9429",
    "temperature": "5575K",
    "mass": "0.93SM",
    "radius": "647559",
    "magnitude": "4.69",
    "planets": "7",
    "moons": "10"
  },
  "Pyraas": {
    "faction": "None",
    "spectralClass": "G5",
    "catalogueId": "NN 3824",
    "temperature": "5575K",
    "mass": "0.93SM",
    "radius": "647559",
    "magnitude": "4.97",
    "planets": "8",
    "moons": "13"
  },
  "Rana": {
    "faction": "None",
    "spectralClass": "F5",
    "catalogueId": "NN 3841",
    "temperature": "6675K",
    "mass": "1.30SM",
    "radius": "835560",
    "magnitude": "3.32",
    "planets": "9",
    "moons": "15"
  },
  "Strix": {
    "faction": "None",
    "spectralClass": "K0",
    "catalogueId": "NN 3868A",
    "temperature": "5200K",
    "mass": "0.78SM",
    "radius": "591855",
    "magnitude": "5.05",
    "planets": "6",
    "moons": "9"
  },
  "Fermi": {
    "faction": "None",
    "spectralClass": "G5",
    "temperature": "5575K",
    "mass": "0.93SM",
    "radius": "647559",
    "magnitude": "4.22",
    "planets": "10",
    "moons": "19"
  },
  "Bohr": {
    "faction": "None",
    "spectralClass": "G5",
    "temperature": "5575K",
    "mass": "0.93SM",
    "radius": "647559",
    "magnitude": "5.42",
    "planets": "8",
    "moons": "7"
  },
  "Huygens": {
    "faction": "None",
    "spectralClass": "F8",
    "temperature": "6180K",
    "mass": "1.18SM",
    "radius": "772893",
    "magnitude": "3.43",
    "planets": "8",
    "moons": "12"
  },
  "Hawking": {
    "faction": "None",
    "spectralClass": "G5",
    "temperature": "5575K",
    "mass": "0.91SM",
    "radius": "632905",
    "magnitude": "5.12",
    "planets": "6",
    "moons": "5"
  },
  "Archimedes": {
    "faction": "None",
    "spectralClass": "F5",
    "temperature": "6675K",
    "mass": "1.30SM",
    "radius": "835560",
    "magnitude": "2.44",
    "planets": "6",
    "moons": "6"
  }
};
